apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
  labels:
    app: todo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: todo-web
          image: todo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-db
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-db
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: DB_PASSWORD
